import { Header } from './components/Header';
import { SectionHome } from './components/SectionHome';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header />
        <SectionHome />
        {children}
      </body>
    </html>
  );
}
