import './globals.css';
import { Inter } from 'next/font/google';
import Heaader from '@/components/Header';
import SectionBanner from '@/components/SectionBanner';
import SectionPersona from '@/components/SectionPersona';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Heaader />
        <SectionBanner />
        <SectionPersona />
        {children}
      </body>
    </html>
  );
}
